apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: vjoseph
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-deployment
        image: harbor.dev.afsmtddso.com/vjoseph-harbor-project/db:2ae8ab6-6e3203b
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: db-secret
