apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: vjoseph
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-deployment
        image: harbor.dev.afsmtddso.com/vjoseph-harbor-project/db@sha256:efae797b6ab498e8726a7aca555dc1620fabd8343d6a97771113fb9255d3ce6e
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: db-secret
